####################
# africa

ao: af           # Angola
bj: af           # Benin
bw: af           # Botswana
bf: af           # Burkina Faso
bi: af           # Burundi
cv: af           # Cape Verde
cf: af           # Central African Republic
td: af           # Chad
km: af           # Comoros
cg: af           # Congo
cd: af           # Congo DR
dj: af           # Djibouti
gq: af           # Equatorial Guinea
er: af           # Eritrea
et: af           # Ethiopia
ga: af           # Gabon
gm: af           # Gambia
gn: af           # Guinea
gw: af           # Guinea-Bissau
ke: af           # Kenya
ls: af           # Lesotho
lr: af           # Liberia
mg: af           # Madagascar
mw: af           # Malawi
ml: af           # Mali
mr: af           # Mauritania
mu: af           # Mauritius
mz: af           # Mozambique
na: af           # Namibia
ne: af           # Niger
rw: af           # Rwanda
st: af           # São Tomé and Príncipe
sn: af           # Senegal
yc: af           # Seychelles
sl: af           # Sierra Leone
so: af           # Somalia
ss: af           # South Sudan
sd: af           # Sudan
sz: af           # Swaziland
tg: af           # Togo
ug: af           # Uganda
tz: af           # Tanzania
zm: af           # Zambia
zw: af           # Zimbabwe
dz: af           # Algeria
eg: af           # Egypt
ma: af           # Morocco
ly: af           # Libya
tn: af           # Tunisia
ci: af           # Côte d'Ivoire
gh: af           # Ghana
ng: af           # Nigeria
cm: af           # Cameroon
za: af           # South Africa

###############################
# dependencies & territories

yt: af      # Mayotte (FR)
re: af      # Réunion (FR)
