require 'hoe'
require './lib/worlddb/version.rb'

## NB: plugin (hoe-man) not required; just used for future testing/development
Hoe::plugin :man   # more options for manifests (in the future; not yet)

Hoe.spec 'worlddb' do
  
  self.version = WorldDB::VERSION
  
  self.summary = 'worlddb - world.db command line tool'
  self.description = summary

  self.urls    = ['http://geraldb.github.com/world.db']
  
  self.author  = 'Gerald Bauer'
  self.email   = 'opensport@googlegroups.com'
    
  # switch extension to .markdown for gihub formatting
  #  - auto-added from Manifest.txt (see define_spec in class Hoe)
  # self.readme_file  = 'README.markdown'
  # self.history_file = 'History.markdown'
  
  self.extra_deps = [
    ['activerecord', '~> 3.2']  # NB: will include activesupport,etc.
    ### ['sqlite3',      '~> 1.3']  # NB: install on your own; remove dependency
  ]
  
  self.licenses = ['Public Domain']

end